version: '3'

services:
  jacow_db:
    image: postgres:12.0
    container_name: jacow-db
    environment:
      POSTGRES_USER: jacow
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: jacow
    volumes:
      - jacow-db-vol:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    image: app
    container_name: app
    environment:
      JACOW_REFERENCES_PATH: /home/jacow/spms
      SPMS_DEBUG: 'False'
      DEV_DEBUG: 'False'
      API_DB_HOST: jacow_db
      API_DB_PORT: 5432
      API_DB_USER: jacow
      API_DB_PASS: docker
      API_DB_NAME: jacow
    ports:
      - "80:5000"
    depends_on:
      - jacow_db

volumes:
  jacow-db-vol:

